name: Automated tests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose tests
        required: true
        default:
        type: choice
        options:
          - tests_for_example_ci

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Start docker container
        run: docker build -t automation-tests .

      - name: Run autotests in docker container
        if: "github.event.inputs.deployment_target == 'tests_for_example_ci'"
        run: docker run automation-tests
        env:
          TP_API_KEY: ${{ secrets.TP_API_KEY }}

      - name: Generate Allure Report
        run: docker cp $(docker ps -a -q | head -1):/example_framework/allure_results .

      - name: Run Allure Report
        run: allure serve allure_results

#      - name: Generate Allure Report
#        uses: simple-elf/allure-report-action@master
#        if: always()
#        id: allure-report
#        with:
#          allure_results: allure-results
#          allure_report: allure-report
#          gh_pages: gh-pages
#          allure_history: allure-history
#
#      - name: Publish report
#        uses: peaceiris/actions-gh-pages@v2
#        if: always()
#        env:
#          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          PUBLISH_BRANCH: gh-pages
#          PUBLISH_DIR: allure-history
